version: '3'
services:
  backend:
    image: "devcamp-backend:1.0"
    build: .
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - APP_ENV=${APP_ENV}

    volumes:
      - type: bind
        source: ./src
        target: /app/src
    restart: unless-stopped
