version: '3'
services: 
  backend:
    build: .
    container_name: "devcamp-backend"
    ports: 
        - "80:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - APP_ENV=${APP_ENV}
    volumes:
        - ./src:/src
    restart: unless-stopped
